version: "2"
services:
  node:
    image: "node:14"
    user: "node"
    working_dir: /usr/src/app/
    environment:
      - NODE_ENV=production
    volumes:
        - ./:/usr/src/app
        - ./node_modules:/usr/src/node_modules
    expose:
      - "3000"
    command: "node index.js"